### ISSUE TITLE
User can search movies

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/movie-journal#1]
## ⚙️ Feature

User can search movies

## 📐 Functionality

The user sees a search input field with which they can type in a keyword for a movie they intend to find.

## 🖼️ Wireframes

![ajax-project-figma-feature-1-mobile](https://user-images.githubusercontent.com/55222182/134239559-ed307fcc-4c63-408f-ba14-d73278f6f4e0.png)
![ajax-project-figma-feature-1-desktop](https://user-images.githubusercontent.com/55222182/134239571-6704eff5-e790-4efd-8d6a-74d369a657ea.png)

## ✅ Task List

- [x] Create the general layout of the wireframe in html and css.
- [x] Ensure the background image is fixed properly.
- [x] Ensure the value of the search is saved in the local storage and data model.
- [x] Ensure the value is used properly in the API request function.
- [x] Ensure mobile responsiveness.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
