### ISSUE TITLE
User can view search results.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/movie-journal#2]
## ⚙️ Feature

User can view search results.
## 📐 Functionality

When the user submits a search keyword, a list of movies is loaded from the OMDb API and displayed on the page.

## 🖼️ Wireframes

![Screen Shot 2021-09-22 at 11 07 44 PM](https://user-images.githubusercontent.com/55222182/134461330-7cf1e2a5-ff0d-40ef-8310-b69910c9c253.png)
![Screen Shot 2021-09-22 at 11 07 33 PM](https://user-images.githubusercontent.com/55222182/134461336-d75f69bc-eba2-4fc1-988e-8f4aceec1b40.png)

## ✅ Task List

- [x] Ensure that each search request is identified with a unique ID for the purpose of editing later.
- [x] Ensure that the data model includes all the relevant data from the search.
- [x] Create a new data-view for the search results view.
- [x] Ensure mobile responsiveness.
- [x] Create search results dummy model for the DOM tree.
- [x] Ensure that a search creates a new DOM tree.
- [x] Ensure that the genre is included in the search results.
- [x] Ensure that previous search results are removed after a new one is done.
- [x] Create a message that describes which keyword the results are for.
- [x] If a poster image is unavailable, ensure a placeholder image is assigned.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
