### ISSUE TITLE
User can add/save a movie to their watchlist.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/movie-journal#3]
## ⚙️ Feature

User can add/save a movie to their watchlist.

## 📐 Functionality

When the user clicks on the add button or the "Add to Watchlist" text, the button will turn green and text "Added to Watchlist!" for a couple of seconds. After that, it will be "View in Watchlist" which the user will be able to click on to view My Watchlist. (The data is now stored in an accessible data model)

## 🖼️ Wireframes

![Screen Shot 2021-09-24 at 10 29 31 AM](https://user-images.githubusercontent.com/55222182/134716653-77ffff3b-7031-4d56-8430-78d136022609.png)
![Screen Shot 2021-09-24 at 10 29 00 AM](https://user-images.githubusercontent.com/55222182/134716657-a4692ef4-b548-47e3-ad03-dfd318c8cfac.png)
## ✅ Task List

- [x] Create event listeners for the buttons and text to visually react when selected, as described above.
- [x] Create storage for the data of the selected card.
- [x] Ensure that the data is pushed into the storage when the card is 'added'.
- [x] Ensure that the data remains locally stored in the browser.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
