### ISSUE TITLE
User can view their watchlist.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/movie-journal#4]
## ⚙️ Feature

User can view their watchlist.
## 📐 Functionality

After the user adds a search result card to their watchlist, they can view their watchlist by either clicking on the same button they used to add it, or clicking on the My Watchlist anchor at the top navigation area.
## 🖼️ Wireframes

![Screen Shot 2021-09-25 at 12 43 02 PM](https://user-images.githubusercontent.com/55222182/134784251-bd085951-b8ef-4409-bc65-d1466d892211.png)

![ajax-project-figma-feature-4-desktop1](https://user-images.githubusercontent.com/55222182/134242811-50dfa14d-7c4a-4145-95a1-b076f3d3ce58.png)
![Screen Shot 2021-09-25 at 12 45 00 PM](https://user-images.githubusercontent.com/55222182/134784299-6dcb224d-7327-4b11-b9d3-cf656720b001.png)

## ✅ Task List

- [x] Create data-view for the watchlist with the header and button to go back. 
- [x] Create the dummy DOM tree model.
- [x] Ensure that the button to go back view swaps properly.
- [x] Ensure that the button "View Watchlist" view swaps properly.
- [x] Ensure that the anchor "My Watchlist" in the top navigation area view swaps properly.
- [x] Create the function for rendering the watchlist DOM tree.
- [x] Ensure that newly added cards appear in the watchlist.
- [x] Ensure that the newly added cards appear in the watchlist without reloading.
- [x] Ensure that the added cards remain in the watchlist after reload.
- [x] If there are no cards in watchlist, display a text, 'Your Watchlist is currently empty.'
- [x] Ensure that selected card in detailed view remains after reload.
- [x] Ensure that a selected card that has already been added to Watchlist shows "In Watchlist".
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
