### ISSUE TITLE
User can rate or leave a note (review/comment) for a movie in their Watchlist.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/movie-journal#5]
## ⚙️ Feature

User can rate or leave a note (review/comment) for a movie in their Watchlist. 
## 📐 Functionality

If the user clicks on a movie card in their Watchlist OR just the pen icon, it will expand in a more detailed view (similar to how it works in the search results view). In this view, the user has the option to rate the movie on a 5-star scale and input some text as notes, ideally acting as a review or comment about the movie.
## 🖼️ Wireframes

![Screen Shot 2021-10-07 at 11 58 49 AM](https://user-images.githubusercontent.com/55222182/136446040-0ade2277-906d-403c-ac92-0754b5826c23.png)

![Screen Shot 2021-10-07 at 11 57 39 AM](https://user-images.githubusercontent.com/55222182/136446058-55aa975d-8b14-4a90-b4ef-a0a23d341387.png)

## ✅ Task List

- [ ] Create the data-view for the expanded movie card view.
- [ ] Create a dummy model for the DOM tree, including more movie info, a 5-star rating, and text area.
- [ ] Ensure view swappable tabs that cycle between the movie summary/plot and the text area for notes.
- [ ] Include a button for editing for the Watchlist cards via DOM rendering.
- [ ] Create an event listener for switching the view to the expanded movie card on the editing button.
- [ ] Ensure that clicking on the editing button renders the respective DOM tree.
- [ ] Ensure that refreshing the page maintains the view.
- [ ] Ensure that clicking on the back button works properly.
- [ ] Ensure that the data model is being updated properly.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Confirm that there are no errors in the console while using the application.
