### ISSUE TITLE
User can remove a movie from their watchlist.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/movie-journal#6]
## ⚙️ Feature

User can remove a movie from their watchist.
## 📐 Functionality

When the user clicks on the remove button for a saved card in their watchlist, that card will be deleted and no longer saved.

## 🖼️ Wireframes

![Screen Shot 2021-09-28 at 9 11 36 PM](https://user-images.githubusercontent.com/55222182/135202006-4adbce61-49a6-40b1-8c3d-55d3895ba51e.png)

![Screen Shot 2021-09-28 at 9 10 24 PM](https://user-images.githubusercontent.com/55222182/135201905-35d94ca7-7791-4b00-af5d-08c31fa23d0a.png)

## ✅ Task List

- [x] Create an icon within a button for each card in the watchlist.
- [x] Create an event listener that displays a modal window for confirmation.
- [x] Ensure that clicking on either button closes it and displays the watchlist.
- [x] Create an event listener for the button click that removes that card DOM as a result.
- [x] Ensure that the card remains removed after reloading or view swapping.
- [x] Ensure that the card is removed from the data model object as well.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Confirm that there are no errors in the console while using the application.
