### ISSUE TITLE
User can select a search result to view more details.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/movie-journal#9]
## ⚙️ Feature

User can select a search result to view more details.

## 📐 Functionality

When viewing the search results, selecting an individual result card will view a bigger card that has more information about the movie, such as the director, cast, and plot summary.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-23 at 11 13 36 AM](https://user-images.githubusercontent.com/55222182/134561614-b793fc13-cc7c-476c-aef0-f0ea62e882c5.png)

![Screen Shot 2021-09-23 at 11 13 58 AM](https://user-images.githubusercontent.com/55222182/134561625-b1ec2ce8-493b-4f4b-8fb4-6af0c2282f11.png)
![Screen Shot 2021-09-23 at 11 14 15 AM](https://user-images.githubusercontent.com/55222182/134561633-62d1f3b2-e598-4584-a12c-cd6272eb90e4.png)

## ✅ Task List

- [x] Create a hidden text element in the search result cards for the imdbID.
- [x] Create a new data-view for the detailed card.
- [x] Add a button element that takes the user back to the search results view.
- [x] Create a dummy model for the DOM tree.
- [x] Ensure that the selected search result matches the detailed card via the imdbID.
- [x] Create the function for rendering the DOM tree.
- [x] Create an event listener for selecting a search result card which will switch to the detailed card view.
- [x] Ensure that clicking the 'back' button takes the user back to the search results view.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
